
<?php
class admin_dashboard_v extends page_v
{
    private $ajax_dashboard_v;
    function __construct()
    {
        $this->ajax_dashboard_v=new ajax_dashboard_v();
        parent::__construct("dashboard","dashboard");

    }
    public function addToInput($key, $value)
    {
        $this->ajax_dashboard_v->addToInput($key,$value); //nu propagai valoare din _V in ajax_v
        parent::addToInput($key, $value); // TODO: Change the autogenerated stub
    }
    function sideBar()
    {
        ?>
        <div class="card">
            <div class="card-header">Edit my profile</div>
            <div class="card-body" id="main_form_parent">
                <?php
                $this->ajax_dashboard_v->addForm();
                ?>
            </div>
            <div class="card-footer"></div>
        </div>
        <?php
    }
    function mainBar()
    {
        ?>
        <div class="card">
            <div class="card-header">My info</div>
            <div class="card-body" id="main_content_parent">
                <?php
                $this->ajax_dashboard_v->display();
                ?>
            </div>
            <div class="card-footer"></div>
        </div>
        <?php
    }
}
