
<?php
class docker_manager_v extends page_v
{
    private $ajax_docker_manager_v;
    function __construct()
    {
        $this->ajax_docker_manager_v=new ajax_docker_manager_v();
        parent::__construct("docker_manager","docker manager");

    }
    public function headCustomScripts()
    {
        ?>
        <script type="text/javascript" src="assets/elearning/docker_manager.js"></script>
        <?php
    }

    public function addToInput($key, $value)
    {
        $this->ajax_docker_manager_v->addToInput($key,$value); //nu propagai valoare din _V in ajax_v
        parent::addToInput($key, $value); // TODO: Change the autogenerated stub
    }
    function sideBar()
    {
        ?>
        <div class="card">
            <div class="card-header">Docker edit</div>
            <div class="card-body" id="docker_form_parent">
                <?php
                $this->ajax_docker_manager_v->addForm();
               // $this->ajax_docker_manager_v->addDocker();
                ?>
            </div>
            <div class="card-footer"></div>
        </div>
        <?php
    }
    function mainBar()
    {
        ?>
        <div class="card">
            <div class="card-header">Docker info</div>
            <div class="card-body" id="docker_content_parent">
                <?php
                $this->ajax_docker_manager_v->display();
                ?>
            </div>
            <div class="card-footer"></div>
        </div>

        <?php
    }

}
