<?php
class exercises_v extends page_v
{
    private $ajax_exercises_v;
    function __construct()
    {
        $this->ajax_exercises_v=new ajax_exercises_v();
        parent::__construct("exercises","exercises");
    }
    function addToInput($key, $value)
    {
        $this->ajax_exercises_v->addToInput($key,$value);
        parent::addToInput($key, $value); // TODO: Change the autogenerated stub
    }

    function headCustomScripts()
    {
        ?>
        <script type="text/javascript" src="assets/elearning/exercises.js"></script>
        <?php
    }
    function headCustomCss()
    {
        ?>
        <link rel="stylesheet" type="text/css" href="assets/elearning/exercises.css">
        <?php
    }

    function sideBar()
    {
       ?>
        <div class="card">
            <div class="card-header">Your query</div>
            <div class="card-body" id="exercises_parent">
                <?php
                $this->ajax_exercises_v->addForm();
                ?>
                <a href="" onclick="loadAjax('index.php','&page=exercises&action=reset','results_parent');return false;" class="btn btn-danger">RESET DATABASE TO DEFAULT</a>
            </div>
        </div>
<?php
    }
    function mainBar()
    {
        ?>
        <div class="card">
            <div class="card-header">Result</div>
            <div class="card-body" id="results_parent">
                <?php
                $this->ajax_exercises_v->display();
                ?>
            </div>
        </div>

<?php

    }
}
