<?php
class quizz_v extends page_v
{
    private $ajax_quizz_v;
    function __construct()
    {
        $this->ajax_quizz_v=new ajax_quizz_v();
        parent::__construct("quizz","Courses Content");

    }

    public function addToInput($key, $value)
    {
        $this->ajax_quizz_v->addToInput($key, $value); //nu propagai valoare din _V in ajax_v
        parent::addToInput($key, $value); // TODO: Change the autogenerated stub
    }

function sideBar()
{
    ?>
    <div class="card">
        <div class="card-header">Your Courses</div>
        <div class="card-body" id="exercises_parent">
            <?php
            $this->ajax_quizz_v->display();
            ?>
        </div>
    </div>
    <?php
    }
}
